### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by ndv87**

### CODE REVIEW

**Comment by SooluThomas** [comment]
This PR is on hold because we haven't opened Russian due to the lack of volunteers.

**Comment by ndv87** [comment]
So why should we wait? Let's start now and people will come!

**Comment by nonhermitian** [comment]
Can you please move this PR here: https://github.com/Qiskit/qiskit-translations

**Comment by ndv87** [comment]
Done https://github.com/Qiskit/qiskit-translations/pull/17

**Pull request closed without merging**
