### PR TITLE
Changing the picture in the documentation landing page

### LINKED ISSUE #2744: Update Header Image on Documentation Landing Page
### Feature description

Looking to update the header image on the [Documentation home page](https://qiskit.org/documentation/) to be more reflective of the current Qiskit brand identity. 

### Additional context

I think there is a header image already developed for this change, just needs to be implemented!

### PR DESCRIPTION
**Pull request by 1ucian0**
Fixes https://github.com/Qiskit/qiskit.org/issues/2744

Screenshot 2022-08-29 at 10 56 59

I squeezed a bit the vertical distribution. Did I break something @JRussellHuffman

### CODE REVIEW

**Review by HuangJunye — COMMENTED** [review]
This image is so much better than the original! Loving it. Do you think we should add links to each modules inside the svg file to the individual module documentation page like it was done in the Contributing to Qiskit page? https://qiskit.org/documentation/contributing_to_qiskit.html#decide-what-to-work-on

**Comment by 1ucian0** [comment]
> Do you think we should add links to each modules inside the svg file to the individual module documentation page like it was done in the Contributing to Qiskit page?

not in this PR. But something to consider.

**Review by HuangJunye — APPROVED** [review]

**Comment by HuangJunye** [comment]
LGTM. I will leave it unmerged in case others have other comments. We can merge it at the end of the week.

**Comment by JRussellHuffman** [comment]
It looks fine to me from the screen. Out of curiosity, are you embedding the png version or the svg version? If possible, I would recommend the svg version for accessibility purposes (eg. screen readers could pull out the text more easily).

**Comment by 1ucian0** [comment]
the svg version

**Comment by 1ucian0** [comment]
With the thump up of @JRussellHuffman , I think it can be merged.

**Comment by JRussellHuffman** [comment]
Great. with it being the SVG, you have my thump up.

**Pull request merged**
