### PR TITLE
Docs: add runtime link to main page

### PR DESCRIPTION
**Pull request by IceKhan13**
### Summary
Add runtime documentation link to main page. 

### Details and comments

Per request from community / digital team we need to add runtime docs link to main page and remove intro section.

Design mock 

Screen Shot 2022-04-06 at 1 47 25 PM

Rendered docs

Screen Shot 2022-04-06 at 1 46 08 PM

### CODE REVIEW

**Comment by IceKhan13** [comment]
@y4izus @techtolentino FYI

**Review by techtolentino — APPROVED** [review]
Thanks for tagging me in this @IceKhan13 — this change looks good to me (if I'm allowed to approve)

👏🏽

**Review by jakelishman — APPROVED** [review]
I'll proxy the above approval, but we should probably make sure that everyone who needs to have write access to this does (perhaps more people on the community/digital team could become `CODE_OWNERS` in the `docs/` folder?).

**Comment by HuangJunye** [comment]
@jakelishman Thanks for the approval. I agree with you. Can you please add me and @y4izus as the code owners for docs? If this should be done in a form of a PR, can you please point me to the file that needs to be changed? Thanks!

**Comment by jakelishman** [comment]
It's probably a two-part step - I've got the power to do both, though.  Please remind me if I've not made a PR by the end of the week.

**Comment by HuangJunye** [comment]
Thank you!

**Pull request merged**
