### PR TITLE
Documentation source code linebreaks

### PR DESCRIPTION
**Pull request by SooluThomas**
fixes #397 requested changes and #394.

@delapuente Thank you!
@eddieschoute Can you please let me know if this update looks fine? Thank you.

### CODE REVIEW

**Comment by eddieschoute** [comment]
I think that's good, though I don't know if the 100 characters will actually fit on a line without scrollbar on a decent-sized resolution. Do you have an example image?

**Comment by SooluThomas** [comment]
There is scrollbar added for source codes.

**Comment by eddieschoute** [comment]
Have you considered making the font size a little bit smaller so it fits?

**Comment by SooluThomas** [comment]
hmm... since I adjusted the width. I didn't change the font size.

**Review by jaygambetta — APPROVED** [review]

**Pull request merged**
