### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by walid-mk**
### Summary
contribution on Qiskit language translation

### Details and comments
contribution on Qiskit language translation

### CODE REVIEW

**Comment by SooluThomas** [comment]
@walid-mk Please sign the CLA

**Comment by walid-mk** [comment]
> @walid-mk Please sign the CLA

hello SooluThomas, actually I don't have a CLA, do I need to be part of the Qiskit team to have one, or could anybody who want to contribute have it with somehow? and thank you.

**Comment by SooluThomas** [comment]
@walid-mk I mean, click on `CLA | not signed yet` in the message from CLAssistant. This will load a page "Contribution License Agreement". Scroll down and you'll find a button `Sign in with GitHub to agree`. Click on it (It might take some time to load). When you return to this pull request you'll see `CLA | signed` and the button for CLA will turn green.

**Comment by walid-mk** [comment]
Cool! gut it. Thanks

**Review by SooluThomas — APPROVED** [review]

**Pull request merged**
