### PR TITLE
Added fix for sphinx_tabs not working

### LINKED ISSUE #688: Sphinx tabs not working
Documentation for [Installing from source](https://qiskit.org/documentation/contributing_to_qiskit.html#installing-terra-from-source) used to have a tab structure which toggles between installation for different operating systems, which is not currently working in the desired way. 

- What is the file name(s) where you found the bug?

   [Contributing to Qiskit file](https://github.com/Qiskit/qiskit/blob/master/docs/contributing_to_qiskit.rst)

- What should the documentation say instead?

   Figure out a way to get the tabs working.

- Are there other related issues or pull requests about this bug?

   sphinx-tabs were added in PR https://github.com/Qiskit/qiskit/pull/346
   The sphinx extension used is ['sphinx_tabs.tabs'](https://github.com/djungelorm/sphinx-tabs).

### PR DESCRIPTION
**Pull request by melvin2016**
Fixes #688 
### Summary
Added fix for sphinx_tabs not working.

Screenshot 2019-11-18 at 12 55 17 AM

### Details and comments
The css files required for sphinx_tabs was not mentioned in the conf.py file.
@SooluThomas

### CODE REVIEW

**Review by delapuente — APPROVED** [review]
Nice catch @melvin2016 , thank you!

**Review by delapuente — DISMISSED** [review]
[According to the documentation](https://github.com/djungelorm/sphinx-tabs#installation), this should not be neccessary. Let's dig into a little bit more.

**Review by SooluThomas — COMMENTED** [review]
Hi @melvin2016! Explicitly adding the `.css` files of sphinx-tabs extension is, of course, a workaround but isn't the best way though. Like @delapuente mentioned, it isn't mentioned in the sphinx-tab documentation either to add those css files.

After further investigation, I came across this [issue](https://github.com/sphinx-doc/sphinx/issues/5434) mentioning the downside of using 
```
html_context = {
   'css_files': ['',]
}
```

So, the best possible solution is to:

- revert the changes that you've made
- add `app.add_css_file('css/theme-override.css')` inside `def setup(app):` which you can find towards the end of the `conf.py` file
- remove `html_context={}`

**Comment by melvin2016** [comment]
@SooluThomas @delapuente pushed commit as proposed, added add_css_file() function.

**Review by SooluThomas — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
