### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
- Removed all content that overlapped with tutorials (Did not do Aqua yet)
- All elements highlighted on same page, and redundant text on main page removed.
- Changed name to highlight that this is API documentation
- Note saying this is API documentation and here is where tutorials are.
- Added link to tutorials in sidebar.

### CODE REVIEW

**Comment by nonhermitian** [comment]
I had to temporarily disable line length checking because the links to the tutorials are very long, and I am unclear as to how to break rst links across multiple lines.

**Comment by mtreinish** [comment]
> I had to temporarily disable line length checking because the links to the tutorials are very long, and I am unclear as to how to break rst links across multiple lines.

Try not using an inline link. Do it like the example in the code box here:

http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#external-links

in this case something like:
```
see the `Qiskit tutorials`_. A link can also be found in the sidebar.

.. _Qiskit tutorials: https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorials/blob/master/qiskit/1_start_here.ipynb

```

**Comment by jaygambetta** [comment]
im approving even though the links need work and same with the elements. As well as the combining of the developer docs

**Review by jaygambetta — APPROVED** [review]

**Comment by nonhermitian** [comment]
To be clear the link is too long no matter where it goes. I think maybe rst substitution several times can also fix it. 

This is a reasonable stop point before thinking of moving all element info into the source code. Perhaps that should be first thing on the list when we do migration.

**Comment by derivation** [comment]
@nonhermitian try [this sphinx extension](https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html) for the crazy long tutorial links. It'll involve editing [this section](https://github.com/Qiskit/qiskit/blob/c4a1bde76576e1fb4a8b99e384c63a3af23506f8/docs/conf.py#L113) of the Sphinx conf.py.

**Comment by SooluThomas** [comment]
> > I had to temporarily disable line length checking because the links to the tutorials are very long, and I am unclear as to how to break rst links across multiple lines.
> 
> Try not using an inline link. Do it like the example in the code box here:
> 
> http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#external-links
> 
> in this case something like:
> 
> ```
> see the `Qiskit tutorials`_. A link can also be found in the sidebar.
> 
> .. _Qiskit tutorials: https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorials/blob/master/qiskit/1_start_here.ipynb
> ```

Inline links can help in better translation. It's better to have inline links so that the names of references can be translated and will point to the same required pages/link targets. More details are available in [GitHub Issue](https://github.com/Qiskit/qiskit/issues/390) #390 .

**Pull request merged**
