### PR TITLE
Homepage in pip package page

### PR DESCRIPTION
**Pull request by 1ucian0**
The [Qiskit pypi page](https://pypi.org/project/qiskit/) has a link for `Homepage` that currently points to the GitHub repo. However, the repo is already pointed by `Source Code`:

So, this PR changes `Homepage` to www.qiskit.org

### CODE REVIEW

**Review by mtreinish — DISMISSED** [review]
It looks like you have unrelated changes to the bib file as part of this PR. Likely you based it on top of #1628 by mistake. This should be cleaned up so this is just the setup.py piece.

**Comment by 1ucian0** [comment]
> It looks like you have unrelated changes to the bib file as part of this PR. Likely you based it on top of #1628 by mistake. This should be cleaned up so this is just the setup.py piece.

shoot. Polluted master in my fork. Fixed it already. Thanks!

**Review by HuangJunye — APPROVED** [review]
LGTM.

**Comment by jakelishman** [comment]
Currently blocked from merge until Terra fixes its docs build, such as by Qiskit/qiskit-terra#9346, but we also still currently pull in IBMQ to document, which also uses `jupyter-sphinx`.  Its usage is far smaller, so we might be able to get away with that until we can remove the package completely.

**Pull request merged**
