### PR TITLE
Fixed a Broken Link In getting_started.html 

### PR DESCRIPTION
**Pull request by divshacker**
### Summary
This is Clearly the Fix of #1194. All the details of this PR can be found in this Issue only 

### Details and comments
I have tried to fix the Problem by correcting the link. 
Please Let me know If any changes needed from my end

### CODE REVIEW

**Comment by divshacker** [comment]
@bopardikasoham

**Comment by divshacker** [comment]
@mtreinish

**Comment by divshacker** [comment]
@SooluThomas  @nonhermitian please review this pr and let me know any further changes

**Review by SooluThomas — APPROVED** [review]

**Comment by divshacker** [comment]
It stil not get merged. Don't know why....

**Comment by divshacker** [comment]
Hey @mtreinish  @nonhermitian  Can you guys Please check this PR why it is not auto merging

**Comment by paniash** [comment]
@divshacker Hi! Please don't post such messages continuously requesting for an immediate review. An open PR is (by definition) going to reviewed at some point owing to the time constraints of the reviewer. 

P.S. This also clutters the project's issue tracker with unnecessary logs. Thanks :-)

**Comment by divshacker** [comment]
> @divshacker Hi! Please don't post such messages continuously requesting for an immediate review. An open PR is (by definition) going to reviewed at some point owing to the time constraints of the reviewer. 
> 
> P.S. This also clutters the project's issue tracker with unnecessary logs. Thanks :-)

Didn't know that it affects the project. 😅
Sorry if any problem is caused by me. I will try not to do it again. Sorry

**Pull request merged**
