### PR TITLE
JKU provider

### PR DESCRIPTION
**Pull request by jaygambetta**

### CODE REVIEW

**Review by yehuda-naveh — COMMENTED** [review]
If we can go with the following (following inputs from JKU)

- **Decision diagram-based quantum simulator**
    - **Organization:** Alwin Zulehner and Robert Wille from Johannes Kepler University, Linz, Austria
    - **Description:** A local provider which allows Qiskit to use decision diagram-based quantum simulation
    - **Qiskit Version:** 0.7
    - **More info:**  `Webpage at JKU <http://iic.jku.at/eda/research/quantum_simulation>`, `Medium Blog <blah>`_ and `Github Repo <https://github.com/Qiskit/qiskit-jku-provider>`_

**Comment by jaygambetta** [comment]
just push directly to the pr

**Comment by yehuda-naveh** [comment]
Cannot, I don't have push access here

**Comment by jaygambetta** [comment]
now?

**Review by yehuda-naveh — DISMISSED** [review]

**Comment by yehuda-naveh** [comment]
Yes, done. Still WIP because need the web address of the Blog. Will do with Leron once online

**Comment by jaygambetta** [comment]
sure -- also there is an error in the linting we also need to fix (too long). @derivation do you know what it is. I tried a few times.

**Review by derivation — DISMISSED** [review]

**Review by derivation — DISMISSED** [review]

**Review by derivation — APPROVED** [review]

**Comment by derivation** [comment]
@diego-plan9 any idea why the build is failing and erroring out on the branch? Is it safe to merge as is?

**Comment by diego-plan9** [comment]
I think it is safe to go ahead and merge - the "Travis CI - Branch" is showing up as the PR is coming from a branch in the repository (as opposed to the fork), but the "really required check" is the other one ("Travis CI - Pull Request").

**Pull request merged**
