### PR TITLE
merge release notes and make coherent

### LINKED ISSUE #239: merge release notes under Aqua ToC tree into release notes at top of ToC
Aqua has its own release notes section https://qiskit.org/documentation/aqua/release_history.html

Should be merged into https://qiskit.org/documentation/release_history.html

### PR DESCRIPTION
**Pull request by derivation**
closes #239

Reformat release notes to create a consistent style across the various 
Qiskit elements using a simplified version of [keep a changelog](https://keepachangelog.com/en/1.0.0/) (also inspired by [MATLAB's release notes](https://www.mathworks.com/help/matlab/release-notes.html))

Here's the format for each element's release notes with the rolled up keep-a-changelog elements in parentheses:

- Highlights (executive summary)
- New Features (added, changed)
- Bug Fixes (fixed, security)
- Compatibility Considerations (deprecated, removed)

### CODE REVIEW

**Comment by jaygambetta** [comment]
can you add notes for 0.10

**Comment by derivation** [comment]
@jagunnels could you add your material to this PR? @lerongil gave me a heads up that you wanted to add some material.

**Comment by jagunnels** [comment]
> @jagunnels could you add your material to this PR? @lerongil gave me a heads up that you wanted to add some material.

I tried (almost valiantly, sometimes successfully) to avoid repeating corrections I had that were already incorporated into the document (there were several).

Here it is:
============================
Terra 0.8
Minor: First bullet in New Features.  Missing Harvard/Oxford comma between 
"and" and "running them on IBMQ devices."  

Minor: First bullet under "In addition there is also ..." (which is, you
know, repetitive, btw) does not have a period after "Cython." 

Minor: "User config files ... " should probably be "User configuration files"
in this format.

Minor: I am not sure why the third (and not the first) appearance of the word
"Cython" is/was hyperlinked.

Not exactly minor: "Terra" and "Qobj" are both inconsistently capitalized as
"free flow text" (i.e. not in quotes, not in "code font," etc.) words.  I think
that it should be "Terra" and "Qobj" (instead of "terra" and "qobj), but, either
way, they should be capitalized consistently. BTW: I think that this also applies
to "non-qobj" (which, I think, should be "non-Qobj").

Minor: In "Cython Components" the word "sdist" should probably be replaced with
"source distribution" in context.

Question: In "Compile Workflow" (which might be better named "Compiler Workflow,"
but I can see the case for what is there) I do not understand why "traspile(), assemble() ..."
are in this funky blue font.  Maybe that changed, but I cannot see it in the PR.

Minor-ish: "qiski.compiler.assemble()" should be "qiskit.compiler.assemble()." [missing "t"]

Minor: In free flow text (i.e. not in quotes or in "code font"), the word "dict" would
probably be better as "dictionary."  

Under "Changes to Visualization"
Major (in a sense): First paragraph: The largest change the the visualization.  "the the"
should be "to the" or "in the."  

Minor: Second paragraph: Instead of these functions just calling ... 
There are a number of ways to rewrite this, but the smallest delta is probably:
Instead of invoking these functions, calling ... 
[At the very least, the word "just" should be removed.]

Minor: Third paragraph: "keys plot_barriers and reverse_bits keys" ... one or the
other of the string "keys" should be removed.  It's dealer's choice ... but one
(not both) should be removed.  Which one is a matter of taste.

Fourth paragraph:
Minor-ish: "The wigner plotting."  As a proper name, I think Wigner is capitalized.
Minor: "the code to use this can" ... "the code to use this feature/functionality/"
Minor-ish: Also, "and not well documented" should be "and were not well documented"
because, at least to me, the prior "were" does not work for this.
(and, yeah, well-documented is often hyphenated, but I think that's a taste thing).

Mapper
"deprecated in this release it will" (missing comma) "deprecated in this release, it will"
"sooner" should be "before that takes place" or "before this transition takes place"

Deprecations (which might have been removed wholesale, not sure):
"to adjust for before the 0.9" ... the word "release" should occur either before
or after (techncally, after) the "(unless otherwise noted)"

First bullet: Ends with trailing words "The methods"
Second bullet: Needs terminal period .
Fourth bullet: "in the in the future" (only one "in the" needed).
Fifth bullet: "a circuit followed by" (missing comma) "a circuit, followed by"
Seventh bullet: "deprecated the" should be "deprecated. The"
Eighth bullet: A few functions ... has ... (the "has" should be "have")

General: All bullet points should probably end in periods.  The missing periods are
not restricted to the few "non-complete sentence" bullets.

Aer 0.2:
New Features
"initialise" should probably be "initialize," but it's an acceptable spelling I suppose.
Final bullet: Addon should be "add-on" or, perhaps, "Add-on."

General: "Qasm" joins "Terra" and "Qobj" in the inconsistent capitalization club.

Aqua 0.5:
Eighth bullet: "entangement" should be "entanglement." Also, the parenthetical
statement after the first period should be "inside" that first sentence (there
is only one sentence ... with a parenthetical statement).
"boolean" should be "Boolean."
I think that the PR fixes the inconsistent text formats of Shor's, Simon's, etc. 
algorithm, but there are bullets that should end in periods that do not.
"hermitian" should be "Hermitian"
If "sized matrices by default" is still there, the initial "Sized" should be capitalized.

Upgrades:
"entanger_map" should be "entangler_map"

I think that where "list of list" appears (more than one place), it should be
"list of lists" even if the STL-type term is singular.  It should even be
"lists of lists" if that applies (I don't know that it does in these instances).

Deprecations:
"Moved Command line" should be "Moved command line" *or* "Moved CLI and GUI ..."
[GUI interfaces is redundant, as, of course, the terminal I stands for Interface.]

**Comment by derivation** [comment]
hold for a bit, need to fix the notes for Qiskit 0.10

**Pull request merged**
