### PR TITLE
Update community page for CQC, and make a small formatting change on roadmap page

### PR DESCRIPTION
**Pull request by Travis-S**
### Summary
The main content of this PR is to add a blurb about CQC's `t|ket>` compiler to the "Additional Passes" section of the community page. This blurb was provided to me by CQC. I also updated the text about circuit optimization to be a bit more clear about what the transpiler architecture is.

There is a small change in the roadmap (formatting), which doesn't alter the content at all.

### CODE REVIEW

**Comment by derivation** [comment]
@Travis-S you've got a few formatting problems you can see in Travis CI

**Review by jaygambetta — DISMISSED** [review]

**Comment by jaygambetta** [comment]
some travis errors

**Comment by Travis-S** [comment]
@derivation @jaygambetta 

My bad on that. I'll pay closer attention to the formatting of RST files in the future. Looks like this request is waiting on a review?

**Comment by jaygambetta** [comment]
i think travis is allowed to get away with travis errors :-)

**Review by derivation — APPROVED** [review]

**Pull request merged**
