### PR TITLE
Migrate `qiskit-ibmq-provider`

### PR DESCRIPTION
**Pull request by Guillermo-Mijares-Vilarino**
### Summary

This PR continues the migration of the qiskit-ibmq-provider repository documentation to a separate page (Qiskit/qiskit-ibmq-provider#1166), this time from the metapackage side.

### Details and comments

* Remove `qiskit-ibmq-provider` from the list of API references built by the metapackage.
* Remove the `deprecate_ibmq_provider` custom extension (it will no longer be necessary)
* Update the link to the documentation (the new page will be created by Qiskit/qiskit-ibmq-provider#1166)
* Remove the section about installing `qiskit-ibmq-provider` from the getting started.
* Remove note about the `RuntimeWarning` from `terra` when `aer` and `ibmq-provider` are not installed. See Qiskit/qiskit-terra#5619.
* Didn't touch the reference to the configuration variables `QISKIT_IBMQ_PROVIDER_LOG_LEVEL` and `QISKIT_IBMQ_PROVIDER_LOG_FILE` from `docs/configuration.rst` in case these still exist.
 
Blocked by Qiskit/qiskit-ibmq-provider#1166

### CODE REVIEW

**Comment by Guillermo-Mijares-Vilarino** [comment]
I believe this is ready to review but still blocked by https://github.com/Qiskit/qiskit-ibmq-provider/pull/1166

**Review by Eric-Arellano — APPROVED** [review]
Thanks, Guillermo! This looks good.

**Review by HuangJunye — APPROVED** [review]
LGTM. Thanks a lot! We can merge as soon as ibmq has its own documentation page.

**Comment by HuangJunye** [comment]
On hold until https://github.com/Qiskit/qiskit-ibmq-provider/pull/1166 is merged and ibmq provider's own documentation page goes live.

**Comment by Guillermo-Mijares-Vilarino** [comment]
Now that Qiskit/qiskit-ibmq-provider#1166 is merged we can remove the `on hold` label.

**Pull request merged**
