### PR TITLE
Update Aer and IBMQ Provider dependencies and bump up Qiskit metapackage version to: 0.11.0

### PR DESCRIPTION
**Pull request by atilag**
### Summary
* Update qiskit-aer version to 0.2.2
* Update qiskit-ibmq-provider to 0.3.0
* Bump up qiskit package to 0.11.0

### CODE REVIEW

**Review by mtreinish — CHANGES_REQUESTED** [review]
Can you also update the version list in docs/release_notes.rst and bump the docs version in docs/conf.py. You can see an example of this in: https://github.com/Qiskit/qiskit/pull/309

We also probably should add a 0.11 entry in the release notes proper just to outline why it's a minor version (ie the ibmq provider changes).

**Comment by chriseclectic** [comment]
@atilag, @quantumjim found a significant bug in Aer 0.2.2. It should be fixed in [this PR](https://github.com/Qiskit/qiskit-aer/pull/280).

Can we merge that in and bump Aer to 0.2.3 before updating the metapackage?

**Comment by nonhermitian** [comment]
The `qiskit-ibmq-provider ` has a bug where updating to the new API causes a loss of job history: https://github.com/Qiskit/qiskit-ibmq-provider/issues/248.

I would wait until that is fixed to bump the version (unless the new API is not included).

**Comment by diego-plan9** [comment]
> The qiskit-ibmq-provider has a bug where updating to the new API causes a loss of job history

For context, it actually seems to be the effect of a change introduced inadvertently in the API in the latest deploy, which the team is working upon and seems an easy fix on their end. Updating to the new API will not cause a loss of job history, nor changes seem to be needed in the provider itself, so hopefully we can proceed while keeping an eye on the API.

**Comment by nonhermitian** [comment]
I would like to verify the jobs are returned before this goes out. Also a few items to do before this can be released.

**Comment by nonhermitian** [comment]
I believe that this is just waiting on the provider to internally grab all the jobs requested by the limit kwarg and then it is ready.

**Review by diego-plan9 — APPROVED** [review]

**Pull request merged**
