### PR TITLE
Component status

### PR DESCRIPTION
**Pull request by jaygambetta**
@ajavadia and @nonhermitian and @diego-plan9 can you look at this and see if the table is correct. 

@chriseclectic can you add a table for the aer provider (this can be a follow-on pr).

### CODE REVIEW

**Comment by derivation** [comment]
@jaygambetta when you call for additional work from others on pull requests you open, would you like the PR to be merged as a minimum viable product and for me to spin up issues, or keep the PR open until the others have added their contributions to it?

**Comment by jaygambetta** [comment]
I am happy to have the minimum viable product and for you to spin up issues. Smaller pr's are always better (fewer conflicts) easier to review.

**Comment by jaygambetta** [comment]
I am also happy for you to edit directly (close or and change). The goal of this is to have something somewhere which says the status of things as people always ask what is stable in qiskit and what is not.

**Comment by diego-plan9** [comment]
The table looks reasonable to me :+1:

**Comment by ajavadia** [comment]
Table looks good. 

I think we can have the compiler interface stable in 0.9 (along with transpiler API).

**Comment by nonhermitian** [comment]
I think this is good.  I thought the visualizations were stable as of last release, but 0.8 is fine as well.

**Review by derivation — APPROVED** [review]
I'll spin up an issue to make sure info on Aer is accurate.

**Comment by jaygambetta** [comment]
ok cool. I'm good to merge this and make aer a follow up. As we need to also make a follow up for aqua (@pistoia )

@derivation when you are good with the structure and such just approve and merge

**Comment by jaygambetta** [comment]
@nonhermitian it is more where it should be located. I think it should be in visualizations not tools/visualizations

**Pull request merged**
