### PR TITLE
Bumping up Aer to: 0.4.1

### PR DESCRIPTION
**Pull request by atilag**

### CODE REVIEW

**Review by mtreinish — CHANGES_REQUESTED** [review]
You need to bump the version of the package itself at L28 here. Also we need to bump the version number for the docs to reflect the new release. You can take a look at https://github.com/Qiskit/qiskit/pull/762 and https://github.com/Qiskit/qiskit/pull/831 for examples of similar bump commits. (you don't have to worry about updating the release notes or rerunning the authors scripts)

**Comment by SooluThomas** [comment]
`docs/index.rst` file should also be updated since the apidoc landing page was renamed from `qiskit_aer` to `aer.rst` (https://github.com/Qiskit/qiskit-aer/pull/639)

**Comment by atilag** [comment]
Thanks!
I think I got it now! (?) :)

**Review by mtreinish — APPROVED** [review]
Thanks for updating this, it LGTM now

**Pull request merged**
