### PR TITLE
Add Abby and Eric as code owners for docs

### PR DESCRIPTION
**Pull request by HuangJunye**
### Summary

Add Abby Mitchell (@javabster) and Eric Arellano (@Eric-Arellano) as code owner of README and docs folder.

### CODE REVIEW

**Comment by HuangJunye** [comment]
Need to add @Eric-Arellano to qiskit github org and give write access to this repo.

**Review by mtreinish — APPROVED** [review]
This LGTM, we should wait on merging until Eric-Arellano is a member of the qiskit org and we add their permissions to the repo

**Comment by Eric-Arellano** [comment]
I'm now a member of the org

**Comment by jakelishman** [comment]
I pressed the manual update on this, then remembered we'd rolled out the automerge to this repo as well.

**Pull request merged**
