### PR TITLE
Initial documentation for tomography

### PR DESCRIPTION
**Pull request by gadial**

### CODE REVIEW

**Comment by derivation** [comment]
@mtreinish any thoughts on the Travis CI error? I'm seeing this in another unrelated PR.

```
ERROR: InvocationError for command '/home/travis/build/Qiskit/qiskit/.tox/lint/bin/pylint -rn --rcfile=/home/travis/build/Qiskit/qiskit/.pylintrc test' (exited with code 4)
___________________________________ summary ____________________________________
ERROR:   lint: commands failed
The command "tox" exited with 1.
```

**Comment by mtreinish** [comment]
@derivation that error is being caused because a new pylint was released today and it (as is typical with every pylint release) changed and/or added new rules which broke us. I'm going to push a patch that adds a pin for the pylint version to the ci jobs. In the meantime I actually have a fix up for this embedded in my larger change here #30

**Comment by derivation** [comment]
@mtreinish Thank you in advance for making a focused PR to add a pin for the pylint version to the ci jobs.

**Review by dcmckayibm — CHANGES_REQUESTED** [review]
This needs to get updated with the latest changes to the Fitter

**Review by dcmckayibm — DISMISSED** [review]

**Review by derivation — APPROVED** [review]

**Comment by derivation** [comment]
@gadial do you think users would benefit from any references to published research these tools were based on?

**Comment by gadial** [comment]
Reference can be helpful (actually, the best reference I can think of is Chris' thesis...) but I'm not sure this document is the correct place; we also have a notebook explaining the theory in more details, and maybe a list of references is more suitable there.

**Pull request merged**
