### PR TITLE
Adding faq

### LINKED ISSUE #111: citation in documentation.

### PR DESCRIPTION
**Pull request by jaygambetta**
Fixes #111

### CODE REVIEW

**Comment by jaygambetta** [comment]
@ajavadia i decided to put the citation under a FAQ. Can you add any other questions you have been asked? Same with you @nonhermitian

**Comment by jaygambetta** [comment]
@derivation also add questions here you think should be. I am just using this a placeholder to get the citation question on the web.

**Comment by derivation** [comment]
Going to keep this open until I hear back from @Travis-S @dongreenberg @jenglick

**Comment by derivation** [comment]
@jaygambetta here's a question that I got from the QStart team. Do you think it's a Qiskit question for the FAQ or an IBM Q services question not fit for the FAQ?

How do the priorities I set correspond to the queuing process for jobs I submit to IBM Q devices?

**Comment by jaygambetta** [comment]
this is a IBM Q questions.

**Comment by derivation** [comment]
Ok. I thought so, too. I'm also reaching out to Anna Obikane who's been synthesizing her observations of the IBM Q Experience user forum https://quantumexperience.ng.bluemix.net/qx/community. At first blush, there are Qiskit related questions on there.

**Comment by jaygambetta** [comment]
sure we can remove the qiskit ones from there

**Comment by derivation** [comment]
From Travis:

- [ ] How do I determine where I am in the queue?
- [ ] When I run a VQE algorithm in Aqua, are the circuits I re-submit with new parameters sent to the back of the queue?
- [x] How can I simulate an Aqua algorithm with noise effects included?

**Pull request closed without merging**
