### PR TITLE
Add QUEKO benchmarks

### PR DESCRIPTION
**Pull request by mtreinish**
### Summary

This commit adds a subset of the QUEKO benchmarks [1] to the benchmark
suite it runs a sweep of different transpiler levels and options on
3 sample circuits (one of each category) and measures the output depth
or the execution time of the transpile.

### Details and comments

[1] https://github.com/UCLA-VAST/QUEKO-benchmark

### CODE REVIEW

**Comment by mtreinish** [comment]
This works locally for me except on sabre with optimization level >= 1 on `bntf` and `bss` it raises a runtime error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/asv/benchmark.py", line 1184, in main_run_server
    main_run(run_args)
  File "/usr/lib/python3.9/site-packages/asv/benchmark.py", line 1058, in main_run
    result = benchmark.do_run()
  File "/usr/lib/python3.9/site-packages/asv/benchmark.py", line 537, in do_run
    return self.run(*self._current_params)
  File "/usr/lib/python3.9/site-packages/asv/benchmark.py", line 766, in run
    return self.func(*param)
  File "/home/mtreinish/git/qiskit/qiskit/test/benchmarks/queko.py", line 196, in track_depth_bss
    return transpile(self.bss, coupling_map=self.rochester_coupling_map,
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 242, in transpile
    circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_args)))
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/tools/parallel.py", line 112, in parallel_map
    return [task(values[0], *task_args, **task_kwargs)]
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/compiler/transpile.py", line 325, in _transpile_circuit
    result = pass_manager.run(circuit, callback=transpile_config['callback'],
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/transpiler/passmanager.py", line 209, in run
    return self._run_single_circuit(circuits, output_name, callback)
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/transpiler/passmanager.py", line 270, in _run_single_circuit
    result = running_passmanager.run(circuit, output_name=output_name, callback=callback)
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 113, in run
    dag = self._do_pass(pass_, dag, passset.options)
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 144, in _do_pass
    dag = self._run_this_pass(pass_, dag)
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/transpiler/runningpassmanager.py", line 156, in _run_this_pass
    new_dag = pass_.run(dag)
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py", line 74, in run
    operator = operator.compose(gate.op)
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/quantum_info/operators/operator.py", line 286, in compose
    indices = [num_indices - 1 - qubit for qubit in qargs]
  File "/home/mtreinish/git/qiskit/qiskit/.asv/env/76391772e92136ec87b9940d70226329/lib/python3.8/site-packages/qiskit/quantum_info/operators/operator.py", line 286, in <listcomp>
    indices = [num_indices - 1 - qubit for qubit in qargs]
TypeError: unsupported operand type(s) for -: 'int' and 'Qubit'
```

**Comment by mtreinish** [comment]
The error the sabre variant of these benchmarks are catching should be fixed by: https://github.com/Qiskit/qiskit-terra/pull/5749

**Comment by ehchen** [comment]
@mtreinish Thanks for doing this so quickly! As you remarked, it'd be helpful to include the optimal depths in the benchmark titles as well.

**Comment by 1ucian0** [comment]
Just a footnote. We should be careful with `HoareOptimizer` (not active in any of the preset pass managers right now) because all these circuits will lose their CX gates, I think.

**Review by ajavadia — APPROVED** [review]

**Pull request merged**
