### PR TITLE
Added a template to automatically add a label to Crowdin Translation

### PR DESCRIPTION
**Pull request by SooluThomas**
### Summary

This commit will automatically add a label ("Localization") and assign a person (me) whenever there's a PR with title "New Crowdin Translations"

My reference: https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository

### CODE REVIEW

**Comment by derivation** [comment]
@SooluThomas are you able to configure the Crowdin bot to use this template?

**Review by mtreinish — CHANGES_REQUESTED** [review]
Doesn't this need to be a PR template instead of an issue template? Also this should be pushed to the `poBranch` branch not master.

**Comment by mtreinish** [comment]
@derivation also raises a good point does the crowdin integration actually respect the template. Just setting a template doesn't mean a PR uses it

**Comment by SooluThomas** [comment]
This doesn't work the intended way. There are bots which auto-labels PR. I'll do the research and make a PR later. Closing this for now.

**Pull request closed without merging**
