### PR TITLE
Qiskit documentation for characterization

### PR DESCRIPTION
**Pull request by yaelbh**
### Summary

Addressing #88

### Details and comments

This is a WIP. So far I wrote the section "Generating Coherence Circuits", but I have to write an additional section "Analyzing the Results".

@dcmckayibm I appreciate if you can:
- Already review what's done so far.
- Write about ZZ.

Thanks!

### CODE REVIEW

**Comment by yaelbh** [comment]
I wrote the Analyzing the Results section. Still need to fill in a few placeholders and fix rst syntax, but the main text is essentially ready.

**Comment by yaelbh** [comment]
Ready for review.
Note that `:math:` is not working, also in https://github.com/Qiskit/qiskit/blob/master/docs/aer/device_noise_simulation.rst.

**Review by dcmckayibm — DISMISSED** [review]

**Comment by yaelbh** [comment]
I fixed a few typos, please check that it's OK.
A couple of unfixed comments:
- "a single qubits data" - not sure if it's correct.
- The Latex/Python expressions towards the end of the document do not display well, at least not in GitHub. Also there is some inconsistency between the expressions, for example one expression has Latex ``\cos`` while the other one has Python ``np.cos``.

**Comment by derivation** [comment]
@yaelbh I'll look into these

**Comment by derivation** [comment]
@yaelbh please review my changes to make sure the last section is still technically valid.

**Comment by yaelbh** [comment]
>  I took the liberty of writing the last two equations in a simpler form. Were there reasons why they were written in the prior form, or is the new form alright?

@dcmckayibm please check the equations.
`:math:` is totally not working for me, and from raw I can't figure what e.g. `a \, e^{-t/{T_2}^*} \, \cos(2\pi ft + \phi) + c` means.

**Comment by derivation** [comment]
@yaelbh for now, https://quicklatex.com/ will let you render the latex code

**Comment by derivation** [comment]
@yaelbh do you think users would benefit from any references to published research these tools were based on?

**Comment by yaelbh** [comment]
@dcmckayibm please see https://github.com/Qiskit/qiskit/pull/160#issuecomment-469382678, thanks

**Comment by dcmckayibm** [comment]
I can't think of a simple reference off the top of my head because these functions are kind of an amalgamation of different sources. We will have some community notebooks with more detail.

**Review by derivation — APPROVED** [review]

**Comment by yaelbh** [comment]
Are the equations correct?

image

**Comment by derivation** [comment]
@yaelbh I rewrote the equations in simpler forms by grouping terms and using trig identities. Are you asking about the mathematical correctness, or the fact that they're not rendering in that screenshot? The doc is rendered in HTML like so: doc

**Comment by dcmckayibm** [comment]
Looks ok

**Pull request merged**
