### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by omarcostahamido**

### CODE REVIEW

**Comment by omarcostahamido** [comment]
question: I'm following these instructions [here](https://qiskit.org/documentation/contributing_to_qiskit.html#contributing-to-documentation). When I get to the step 4/5 is the only option to contribute to JP only? I would like to start contributing to PT-PT.

**Comment by SooluThomas** [comment]
@omarcostahamido That's because we haven't yet enabled Portuguese translations. Please create an Issue for PT translations. Thank you.

**Comment by omarcostahamido** [comment]
done ;)

**Comment by SooluThomas** [comment]
Will reopen when PT translations are enabled

**Comment by SooluThomas** [comment]
@omarcostahamido PT-PT translation in CrowdIn has been enabled. Please follow Step 5 and 6 in [here](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) to complete the process. Thank you.

**Review by derivation — APPROVED** [review]

**Comment by omarcostahamido** [comment]
Thank you @SooluThomas and @derivation 😃

**Pull request merged**
