### PR TITLE
Entanglement verification tutorial

### PR DESCRIPTION
**Pull request by yehuda-naveh**
### Summary
Advanced tutorial for using the entanglement verification features introduced with Ignis 0.3. 
Will keep WIP till 0.3 is out because dependent on it

### CODE REVIEW

**Comment by yehuda-naveh** [comment]
Just did the final adjustments to 0.3, this is ready from my side

**Comment by nonhermitian** [comment]
Can you move this to the Qiskit tutorials repo here: https://github.com/Qiskit/qiskit-tutorials

However, this notebook currently throws an error here:

```python
F = quantum_info.state_fidelity(psi_exp,tomo.fit())
```

```python
QiskitError: 'Input quantum state is not a valid'
```

**Comment by yehuda-naveh** [comment]
I'm not able to reproduce it, it runs successfully on many trials at my end. Any additional info?

**Comment by yehuda-naveh** [comment]
If you can provide psi_exp and the job.result() that produces it, it may help

**Comment by nonhermitian** [comment]
Terra master throws that error.  So I am guessing this tutorial will break on the next Qiskit version (tomorrow) as well.

**Comment by yehuda-naveh** [comment]
I see. If it doesn't throw on stable, let's wait for the release then. I'll figure out what changed when I'll see the fall

**Comment by nonhermitian** [comment]
The error looks to be an issue with the positive-definite calculation in Terra.  Once that is worked out, this should be reopened in https://github.com/Qiskit/qiskit-tutorials.

**Comment by yehuda-naveh** [comment]
@nonhermitian any issue number in Terra? So I'll keep track

**Pull request closed without merging**
