### PR TITLE
Bumping up Qiskit to: 0.12.0

### PR DESCRIPTION
**Pull request by atilag**
### Summary

This PR prepares for the Qiskit `0.12.0` release. This includes new versions of
Terra (0.9.0), Aer (0.3.0), Ignis (0.2.0), and Aqua (0.6.0).

### Details and comments

Co-authored-by: Matthew Treinish <mtreinish@kortar.org>

### CODE REVIEW

**Comment by mtreinish** [comment]
Marking this as on hold since we're going to be pushing releases of the other elements very soon

**Comment by atilag** [comment]
Yep, let's reuse this PR to add the rest of the components when they are ready so we only bump up minor once.

**Comment by mtreinish** [comment]
Ok, terra added. Still waiting on ignis and aqua to release before we can remove the on hold here

**Comment by mtreinish** [comment]
Ignis (the commit message has a copy paste error) has been added as well, now just need aqua

**Comment by mtreinish** [comment]
All elements have been released so this should be good to go now

**Review by nonhermitian — APPROVED** [review]

**Pull request merged**
