### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by robertxdw**
I added the list of French translators, please update, thank you

### CODE REVIEW

**Comment by SooluThomas** [comment]
Hi @robertxdw! Sorry for the inconvenience caused. All the Localization requests will be handled in a different repository - https://github.com/Qiskit/qiskit-translations. Please open a PR and update the Localization Contributors file in qiskit-translations repo. Thank you!

**Comment by robertxdw** [comment]
Hi Soolu Thomas,

Thank you foryour mail

When I clic on the "pen" to add my name (image below), I get a message :  
You’re editing a file in a project you don’t have write access to. 

Is it normal ?

Thanks





Regards / Cordialement 



Robert Wang
 17 Avenue De L'europe

PhD, Consultant & IBM Quantum Ambassador
 Bois Colombes Cedex, 92275
Advanced Analytics, Global Business Services

Mobile:
+33 (0) 6 76 05 89 90
 

e-mail:
robert.wang@fr.ibm.com

**Comment by SooluThomas** [comment]
I'm not sure why that's happening. Can you please try creating a fork and update the list and create a PR. Also, I don't see any Localization requests for French (https://github.com/Qiskit/qiskit-translations/issues). Creating issues can help in finding more people to volunteer for French translations. Can you please open one? Thank you!

**Comment by robertxdw** [comment]
Hi Soolu Thomas,

I added  only my own name, should I click on "Create pull request" ?

Thanks




Regards / Cordialement 



Robert Wang
 17 Avenue De L'europe

PhD, Consultant & IBM Quantum Ambassador
 Bois Colombes Cedex, 92275
Advanced Analytics, Global Business Services

Mobile:
+33 (0) 6 76 05 89 90
 

e-mail:
robert.wang@fr.ibm.com

**Pull request closed without merging**
