### PR TITLE
Bump Applications minimum versions

### PR DESCRIPTION
**Pull request by manoelmarques**
### Summary
Following the recent release 0.3.0 of all application modules, bumping their minimum versions in the meta-package.

### CODE REVIEW

**Review by jakelishman — APPROVED** [review]
Looks fine to me.  Do we need a bump on Experiments to 0.2 as well?

**Comment by manoelmarques** [comment]
@jakelishman I don't know why `qiskit-experiments` doesn't have a min.version test. We update the apps. in the meta-package in order to make it easier for the user to upgrade. I would think `qiskit-experiments` should follow the same principle. I can ammend this PR adding the test there as well.

**Comment by jakelishman** [comment]
Sure - I'll bring it up with Chris to check, but chances are we'll want it, and I'll just add it in as part of the next release which will put out Aer 0.10 (and 0.10.1) and IBMQ-Provider (probably 0.18.3).

**Comment by manoelmarques** [comment]
Thanks, just le me know in Slack if it is ok and I will add it to this PR.

**Pull request merged**
