### PR TITLE
Move to jupyter_sphinx for executing code snippets

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Move to jupyter_sphinx for executing code snippets in `getting_started` and `install`.

### CODE REVIEW

**Comment by jaygambetta** [comment]
can you show a screen shot

**Comment by nonhermitian** [comment]
Here is a sub-section.  The code in the docs is now executed at build via Jupyter.  This gets around some issues with the other IPython version that was making figures not display correctly.

Screen Shot 2019-10-12 at 4 17 54 AM

**Comment by nonhermitian** [comment]
@jaygambetta we good?

**Review by SooluThomas — APPROVED** [review]

**Comment by SooluThomas** [comment]
Fixes #448

**Pull request merged**
