### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by AlexAlper**

### CODE REVIEW

**Comment by SooluThomas** [comment]
Thank you for your interest in contributing to Qiskit translations. Please go ahead and follow [steps 4, 5 and 6](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) in the Contributing to Qiskit documentation.

**Comment by AlexAlper** [comment]
I want to translate into Russian, but it is not in the list. I create a new issue.Now waitingBest regards,Alexander09.10.2019, 01:50, "SooluThomas" <notifications@github.com>:Thank you for your interest in contributing to Qiskit translations. Please go ahead and follow steps 4, 5 and 6 in the Contributing to Qiskit documentation.

**Comment by SooluThomas** [comment]
@AlexAlper As mentioned in the issue that you've opened, (https://github.com/Qiskit/qiskit/issues/616), we need more volunteers to start a language localization. Thank you for your interest again 😊

**Comment by lzdanski** [comment]
Added `on hold` label because we have do not have enough volunteers to open Russian for translation yet.

**Comment by ndv87** [comment]
Hello, i want join.

**Review by ndv87 — COMMENTED** [review]
Added lead translator

**Comment by SooluThomas** [comment]
@ndv87 If you'd like to join, please follow the steps mentioned [here](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation). We haven't opened Russian for translations yet, due to the lack of volunteers. More updates on this will be posted under Issue https://github.com/Qiskit/qiskit/issues/616. Thank you for your interest in this localization effort. 😊

**Comment by ndv87** [comment]
I created PR https://github.com/Qiskit/qiskit/pull/824.

**Comment by nonhermitian** [comment]
Can you please move this PR here: https://github.com/Qiskit/qiskit-translations

**Pull request closed without merging**
