### PR TITLE
Add Huang Junye and Lidia Luna Puerta to the list of contributors

### PR DESCRIPTION
**Pull request by HuangJunye**
### Summary
Add Huang Junye and Lidia Luna Puerta to localisation contributors

### CODE REVIEW

**Review by SooluThomas — COMMENTED** [review]
Hi @HuangJunye! We require every translator to make their own Pull Request so that they sign the CLA too. We'll be specifying this in the documentation too. Sorry about the confusion. Can you please edit your PR?

**Comment by HuangJunye** [comment]
> Hi @HuangJunye! We require every translator to make their own Pull Request so that they sign the CLA too. We'll be specifying this in the documentation too. Sorry about the confusion. Can you please edit your PR?

I realise this after making the PR. Thanks for helping to remove the other name.

**Comment by SooluThomas** [comment]
Issue #610

**Comment by lzdanski** [comment]
@HuangJunye Wrapping up some details about adding Chinese still so I've added the `on hold` label. Will keep you updated!

**Comment by HuangJunye** [comment]
@lzdanski No problem. Thanks for letting me know.

**Comment by nonhermitian** [comment]
Can you please move this PR here: https://github.com/Qiskit/qiskit-translations

**Pull request closed without merging**
