### PR TITLE
Update LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by ignaziopedone**

### CODE REVIEW

**Comment by SooluThomas** [comment]
Thank you for your interest in contributing to Qiskit translations. Please go ahead and follow [steps 4, 5 and 6](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) in the Contributing to Qiskit documentation.

**Comment by ignaziopedone** [comment]
I’m just waiting the adding of italian language. Afterwards, I’ll continue asap.

**Comment by lzdanski** [comment]
Added the `On Hold` label until Italian is added.

**Comment by lzdanski** [comment]
Duplicate PR: #789, #783 

Closing.

**Pull request closed without merging**
