### PR TITLE
I candidate myself for LOCALIZATION_CONTRIBUTORS

### PR DESCRIPTION
**Pull request by arbiter1elegantiae**

### CODE REVIEW

**Comment by SooluThomas** [comment]
Thank you for your interest in contributing to Qiskit translations. Please go ahead and follow [steps 4, 5 and 6](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) in the Contributing to Qiskit documentation.

**Comment by SooluThomas** [comment]
@arbiter1elegantiae Please go ahead and follow [steps 4, 5 and 6](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) in the Contributing to Qiskit documentation section. 

This PR will be closed if we don't receive joining request in CrowdIn.

**Comment by lzdanski** [comment]
@arbiter1elegantiae I don't see your request to join the Qiskit translation project on Crowdin. 

Please go ahead and follow [steps 4, 5 and 6](https://qiskit.org/documentation/contributing_to_qiskit.html#translating-documentation) in the Contributing to Qiskit documentation.

If we don't receive your request in Crowdin by February 1, 2020, this pull request will be closed and you will need to open a new one.

**Comment by lzdanski** [comment]
I see you're waiting for Italian to be added. We are still waiting for a proofreader to volunteer before this project is opened on Crowdin. 

Putting this PR `on hold`

https://github.com/Qiskit/qiskit/issues/600

**Comment by lzdanski** [comment]
Duplicate of #786. Closing.

**Pull request closed without merging**
