### PR TITLE
Fixed typos, removed duplicates, authors listed alphabetically by last name

### PR DESCRIPTION
**Pull request by pistoia**
### Summary
Same names were misspelled and some were duplicated.  Also reordered authors in alphabetical order by last name as per issue [#58](https://github.com/Qiskit/qiskit/issues/58)

### Details and comments
Removed typos and duplicates.
Listed authors alphabetically by last name.

### CODE REVIEW

**Comment by jaygambetta** [comment]
can you do it in the author file and then run https://github.com/Qiskit/qiskit/blob/master/tools/generate_bibtex.py

**Comment by jaygambetta** [comment]
also @ajavadia and @pistoia the special characters will not work in latex so we may need to edit the script

**Comment by ajavadia** [comment]
Yes @pistoia can you please edit this file: https://github.com/Qiskit/qiskit/blob/master/AUTHORS

I already did some manual clean up on that but looks like I missed a few.

Then the script that Jay mentioned will generate the bibtex entry automatically.

**Comment by pistoia** [comment]
@ajavadia is it OK if I use the same list of authors from the BibTeX file?  I had already cleaned that up and ordered it in alphabetical order by last name.

**Comment by ajavadia** [comment]
Sure I think you can just take what you already did and drop it in the AUTHORS file. Then run the script on that to generate the bibtex. I don’t think the bibtex should be done manually. Thanks!

**Comment by cbjuan** [comment]
So, the `AUTHORS` file should be (including [Diego's comment](https://github.com/Qiskit/qiskit/issues/64#issuecomment-460368039)):

```
Abigail J. Cross
Antonio D. Corcoles-Gonzales
Antonio Mezzacapo
Abdón Rodríguez Davila
Adenilton Silva
Adrian Chen
Albert Frisch
Ali Javadi-Abhari
Andreas Fuhrer
Andrew Cross
Anna Phan
Anton Karazeev
Borja Godoy Gago
Charles Taylor
Chris Schnabel
Christophe Vuillot
Christopher Wood
Chun-Fu Chen
David Bucher
David McKay
Delton Ding
Desiree Vogt-Lee
Diego Moreda
Donny Greenberg
Douglas T. McClure
Eddie Schoute
Enrique de la Torre
Eugene Dumitrescu
Fran Cabrera
Giacomo Nannicini
Hanhee Paik
Hiroshi Horii
Hitomi Takahashi
Ikko Hamamura
Ismail Yunus Akhalwaya
Ivan Duran
Jerry M. Chow
Jay Gambetta
Jessica Wilson
Jesús Pérez
Joe Hellmers
John A. Smolin
Jonathan A. Wildstrom
Jorge Carballo
Juan Cruz-Benito
Juan Gomez
Kenso Trabing
Kevin Krsulich
Lee James O'Riordan
Luciano Bello
Manoel Marques
Marco Pistoia
Mark Everitt
Mathias Soeken
Matthew Treinish
Max Reuter
Mingi Ryu
Paco Martín Fernández
Paul Nation
Peng Liu
Pete Taylour
Pieter Eendebak
Richard Chen
Rudy Raymond
Salvador de la Puente González
Seyon Sivarajah
Shaohan Hu
Srujan Meesala
Stefan Woerner
Steve Wood
Takashi Imamichi
Thomas Alexander
Viktor Prutyanov
Vojtech Havlicek
Wes Turner
Yukio Siraichi
Yunho Maeng
Yunong Shi
Chris Culver
Erick Winston
Gadi Aleksandrowicz
Ismael Faro
Toshinari Itoko
Naoki Kanazawa
Ninad Sathaye
Yael Ben-Haim
Yang Luh
Łukasz Herok
```

If approving PR #65, we don't need to order the authors' file manually. I don't add this to the PR because lack of permissions in @pistoia's fork and not in another PR to avoid more noise.

**Review by ajavadia — DISMISSED** [review]

**Comment by ajavadia** [comment]
Thanks @pistoia! Shoudl we remove the special characters as Jay mentioned, since they won't render correctly in Latex?

**Comment by jaygambetta** [comment]
yeah can we drop the special characters or make them latex or something so it renders. This will error in latex

**Comment by pistoia** [comment]
@jaygambetta this update to the PR takes care of the three issues you raised:

1. Author name entries in the `AUTHORS` file are listed alphabetically by last name.
2. The corresponding `Qiskit.bib` file is automatically generated using the `generate_bibtex.py` script.
3. The `generate_bibtex.py` has been updated in order to translate special characters (e.g. accented letters, etc.) from UTF8 to LaTeX.

Notice that:
- It is sufficient to run the `generate_bibtex.py` script from the `tools` folder; it will automatically locate `AUTHORS` and save `Qiskit.bib` in the parent folder.
- The `requirements.dev.txt` file has been update to include the UTF8-to_LaTeX converter, `pylatexenc`.
- @diego-plan9 's [comment](https://github.com/Qiskit/qiskit/issues/64) has been addressed.

**Review by jaygambetta — APPROVED** [review]

**Pull request merged**
