### PR TITLE
fixing broken link

### PR DESCRIPTION
**Pull request by jaygambetta**

### CODE REVIEW

**Comment by SooluThomas** [comment]
If this PR gets approved, do we need a redundant tutorials link in the TOC of docs? 

Screen Shot 2019-08-17 at 7 38 51 PM

**Comment by jaygambetta** [comment]
I agree. I would be ok removing the tutorials link either in the toc or in web. But then we need to remove from qiskit.org. Up to you and @nonhermitian and @derivation

**Comment by jaygambetta** [comment]
But I don’t think we should have a broken link so I would approve and make an issue about how many

**Review by SooluThomas — APPROVED** [review]
Okay. LGTM. I'll create a PR for removing tutorials from TOC.

**Comment by nonhermitian** [comment]
Lets remove the sidebar one.

**Comment by jaygambetta** [comment]
Sounds good. Can you approve @SooluThomas Pr

**Pull request merged**
