### PR TITLE
Docs/pulse builder interface

### PR DESCRIPTION
**Pull request by taalexander**
### Summary
Builds on #872. This is the documentation for the [pulse builder interface](https://github.com/Qiskit/qiskit-terra/pull/4174).

### CODE REVIEW

**Comment by nonhermitian** [comment]
The tutorials are being moved back to their original location for a variety of reasons.  However, there is a lot of content here that can go into module level, or function / class level Qiskit docs.  e.g. `Play` examples can easily be inserted here: https://qiskit.org/documentation/stubs/qiskit.pulse.Play.html#qiskit.pulse.Play

**Comment by taalexander** [comment]
Ok, do you wish to duplicate this content between the tutorials and the docstrings?

**Comment by nonhermitian** [comment]
Nope tutorials need to be lighter. Much content can be moved to docs

**Comment by nonhermitian** [comment]
They just need to show how to accomplish a specific task. The “learning” part can be in the docs

**Comment by nonhermitian** [comment]
Closing as all of this already in the tutorials awaiting next version of Qiskit to be released.

**Pull request closed without merging**
